// MIT License
//
// Copyright (c) 2022 - present Open Swoole Group
// Copyright (c) 2018 SpiralScout
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package php

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	desc "google.golang.org/protobuf/types/descriptorpb"
	plugin "google.golang.org/protobuf/types/pluginpb"
)

const clientTemplate = `<?php declare(strict_types=1);
# Generated by the OpenSwoole compiler. DO NOT EDIT!
# source: {{ .File.Name }}
{{ $ns := .Namespace -}}
{{if $ns.Namespace}}
namespace {{ $ns.Namespace }};
{{end}}
use OpenSwoole\GRPC;
{{- range $n := $ns.Import}}
use {{ $n }};
{{- end}}

{{ $package := .File.Package -}}
{{ $svc := .Service.Name -}}

class {{ .Service.Name | client }} extends \OpenSwoole\GRPC\BaseStub
{
{{- range $m := .Service.Method}}

{{if $m.ServerStreaming}}
	/**
    * @param {{ name $ns $m.InputType }} $request
    * @return {{ name $ns $m.OutputType }}
    *
    * @throws \OpenSwooleGRPC\Exception\InvokeException
    */
    public function {{ $m.Name }}({{ name $ns $m.InputType }} $request, $metadata = []): {{ name $ns $m.OutputType }} {
    	return $this->_serverStreamRequest('/{{ $package }}.{{ $svc }}/{{ $m.Name }}',
        $request,
        ['\{{ $ns.Namespace }}\{{ name $ns $m.OutputType }}', 'decode'],
        $metadata); 
    }

    public function getNext(): HelloReply
    {
        return $this->_getData();
    }
{{- else}}
    /**
    * @param {{ name $ns $m.InputType }} $request
    * @return {{ name $ns $m.OutputType }}
    *
    * @throws \OpenSwooleGRPC\Exception\InvokeException
    */
    public function {{ $m.Name }}({{ name $ns $m.InputType }} $request, $metadata = []): {{ name $ns $m.OutputType }} {
    	return $this->_simpleRequest('/{{ $package }}.{{ $svc }}/{{ $m.Name }}',
        $request,
        ['\{{ $ns.Namespace }}\{{ name $ns $m.OutputType }}', 'decode'],
        $metadata); 
    }
{{end -}}

{{end -}}
}
`

func clientbody(req *plugin.CodeGeneratorRequest, file *desc.FileDescriptorProto, service *desc.ServiceDescriptorProto) string {
	out := bytes.NewBuffer(nil)

	data := struct {
		Namespace *ns
		File      *desc.FileDescriptorProto
		Service   *desc.ServiceDescriptorProto
	}{
		Namespace: newNamespace(req, file, service),
		File:      file,
		Service:   service,
	}

	tpl := template.Must(template.New("clientTemplate").Funcs(template.FuncMap{
		"client": func(name *string) string {
			return identifier(*name, "client")
		},
		"name": func(ns *ns, name *string) string {
			return ns.resolve(name)
		},
	}).Parse(clientTemplate))

	err := tpl.Execute(out, data)
	if err != nil {
		panic(err)
	}

	return out.String()
}

func clientfilename(file *desc.FileDescriptorProto, name *string) string {
	ns := namespace(file.Package, "/")
	if file.Options != nil && file.Options.PhpNamespace != nil {
		ns = strings.ReplaceAll(*file.Options.PhpNamespace, `\`, `/`)
	}

	return fmt.Sprintf("%s/%s.php", ns, identifier(*name, "client"))
}
